### ISSUE TITLE
There’s an error in the example.

### ISSUE THREAD

**Issue by wanliyunyan** [cybozu/WebUI#34]
```

                WebView(configuration: viewState.configuration)
                    .uiDelegate(viewState)
                    .navigationDelegate(viewState)
                    .allowsInspectable(true)
                    .allowsBackForwardNavigationGestures(true)
                    .allowsLinkPreview(false)
                    .refreshable()
                    .border(Color.gray)

Incorrect argument label in call (have 'configuration:', expected 'webView:')
Cannot convert value of type 'WKWebViewConfiguration' to expected argument type 'WKWebView'
Value of type 'WebView' has no member 'uiDelegate'


```

**Comment by elmetal** [comment]
Thank you for the report.
Could you confirm if you're referring to an issue with building the included Example project? 
CI is passing, so the build is successful in the CI environment. Also, could you let me know the macOS, Xcode, and Swift versions where your error reproduces?

**Comment by wanliyunyan** [comment]
macos 15.0.1 ， xcode 16 ，swift 5 ， Normally, Xcode 16 corresponds to Swift 6, but I’ve changed the Swift version on my computer to Swift 5.

**Comment by elmetal** [comment]
There may be an issue with the consistency between Xcode and toolchain versions.
Could you try setting the Swift version on your computer to 6 and see if that resolves the issue?

**Comment by wanliyunyan** [comment]
swift is ok

**Comment by wanliyunyan** [comment]
xcode 16 and swift 6  is not OK

**Comment by wanliyunyan** [comment]
When I paste the files AppDelegate, ContentView, ContentViewState, and ExamplesApp from your example into my own project, I get this error.

**Comment by Kyome22** [comment]
> When I paste the files AppDelegate, ContentView, ContentViewState, and ExamplesApp from your example into my own project, I get this error.

From reading the warning below, it appears that there is another type with the same name as WebUI's `WebView`.
`Incorrect argument label in call (have 'configuration:', expected 'webView:')`
WebUI's `WebView` has never provided an initializer that takes `WKWebView` as an argument.

**Comment by wanliyunyan** [comment]
I can't believe I made such a stupid mistake.
